import React from 'react'
import home from '../assets/Background/bg.svg'
import Tittle from '../assets/Background/title.svg'
import Image from 'next/image'
import Jeep from '../assets/Background/219400.jpg'
import Head from "next/head";
import Navbar from "../components/Navbar/Navbar";

// import { FaGithub, FaLinkedinIn } from 'react-icons/fa';

const test = () => {
  return (
  <>
  <div>
        <Head>
          <title>GMAD 2022</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="../public/favicon.ico" />
        </Head>
        <Navbar />
      </div> 
    <div id="test" className='bg-gray-100 text-gray-900 relative overflow-hidden -space-y-28' >
       {/*Main Event */}

       <div className=' relative items-center w-full  pt-10 bg-cover translate-y-2' style={{ backgroundImage: `url(${home.src})`}}>
       <img  className=' mx-auto px-5 relative flex mt-5 w-auto h-auto' src={Tittle.src}></img>
          <div   className=' relative flex justify-center'>
            
            <div className=' text-white lg:grid lg:grid-cols-2 gap-10 h-1/5 w-3/4  rounded-3xl p-12 mb-48'>
            <div className='  order-2 md:order-1 top-16 flex items-center flex-wrap '>
                <div className=' p-5 sm:p-10 backdrop-blur-3xl rounded-3xl outline outline-2 outline-white/50 ' >
                <img  className=' mx-auto min-w-[100px] min-h-[50px] md:px-5 relative flex mt-5 w-auto h-auto' src={Jeep.src}></img>
                <h1>
                  test
                </h1>
                <h2>
                  test
                </h2>
                  <p className=' py-4 md:text-xl text-justify w-full'>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt expedita ducimus eligendi sit culpa necessitatibus repellat, eos harum impedit accusantium blanditiis eaque, vitae nemo ratione neque. Deleniti illum laborum ab. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla vero esse, quibusdam molestias doloribus deserunt dignissimos. Est dolor repellat alias excepturi! Harum minus ipsam commodi fugiat error fuga porro ad!

                  </p>
                </div>
                
              </div>
              <div className='order-2 md:order-1 top-16 flex items-center flex-wrap '>
                <div className='p-10 backdrop-blur-3xl rounded-3xl outline outline-2 outline-white/50 ' >
                <img  className=' mx-auto px-5 relative flex mt-5 w-auto h-auto' src={Jeep.src}></img>
                <h1>
                  test
                </h1>
                <h2>
                  test
                </h2>
                  <p className=' py-4 md:text-xl text-justify w-full'>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus, ipsa explicabo. Obcaecati, est quas nemo temporibus rem nostrum inventore aliquid maxime sequi modi delectus, numquam explicabo quidem iure. Nam, dolores! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam modi expedita, accusamus sit natus consequatur voluptatibus cumque. Quas est corporis assumenda! In eligendi esse blanditiis aspernatur! Sunt ducimus ratione sint!

                  </p>
                </div>
                
              </div>

              </div>
            </div>
          </div>
          
          {/*Competition */}
          <div className=' relative items-center  pt-10 bg-cover translate-y-2' style={{ backgroundImage: `url(${home.src})`}}>
       <img  className=' mx-auto px-5 relative flex mt-5 w-auto h-auto' src={Tittle.src}></img>
          <div   className=' relative flex justify-center'>
            
            <div className=' lg:grid lg:grid-cols-2  h-1/5 w-3/4 rounded-3xl p-6 mb-48'>
            <div className='  order-2 md:order-1 top-16 flex items-center flex-wrap '>
                <div className=' justify-center align-center items-center p-10 backdrop-blur-3xl rounded-3xl   text-white' >
                  <div className=' mx-auto relative sm:p-10 rounded-3xl py-5 outline outline-2 outline-white/50 text-white '>
                  <img  className=' mx-auto px-5 relative flex mt-5   sm:w-auto sm:h-auto' src={Tittle.src}></img>
                    </div>
                    <h2 className='font-bold py-8 text-center w-full'>
                      Accounting Talk (A-Talk)
                    </h2>
                  <p className=' py-8 text-xl md:text-3xl text-center  w-full'>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident accusantium nobis magnam exercitationem cumque pariatur consequuntur, adipisci, consequatur ad ullam dicta iure! Ipsum suscipit sequi veniam rem labore sapiente ipsa.

                  </p>
                  <div className=' mx-auto h-[70px] relative w-[150px] xl:w-[400px] sm-w-[200px] py-4 rounded-[48px] justify-center items-center align-center outline outline-2 outline-white/50 text-black bg-[#fceb8f]'>
                    <p className='my-auto text-center font-bold text-xl xl:text-3xl'>
                      Register Now
                    </p>
                    
                  </div>
                </div>
                
              </div>
              <div className='  order-2 md:order-1 top-16 flex items-center flex-wrap '>
                <div className=' justify-center align-center items-center p-10 backdrop-blur-3xl rounded-3xl  text-white' >
                  
                    <h2 className='font-bold py-8 text-center w-full'>
                      Accounting Talk (A-Talk)
                    </h2>
                  <p className=' py-8 text-xl md:text-3xl text-center  w-full'>
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt natus assumenda sapiente laborum adipisci nemo ut necessitatibus error doloremque quasi sint, iusto unde corporis sequi porro mollitia sunt repellat incidunt?

                  </p>
                  <div className=' mx-auto h-[70px] relative w-[150px] xl:w-[400px] sm-w-[200px] py-4 rounded-[48px] justify-center items-center align-center outline outline-2 outline-white/50 text-black bg-[#fceb8f]'>
                    <p className='my-auto text-center font-bold text-xl xl:text-3xl'>
                      Register Now
                    </p>
                    
                  </div>
                  <div className=' mx-auto mt-5 relative sm:p-10 rounded-3xl py-5 outline outline-2 outline-white/50 text-white '>
                  <img  className=' mx-auto px-5 relative flex mt-5   sm:w-auto sm:h-auto' src={Tittle.src}></img>
                    </div>
                </div>
                
                
              </div>

              </div>
            </div>
          </div>
          {/*Section For Social Media, Contact and Partnership */}
          <div className=' relative items-center h-[720px]  pt-10 bg-cover translate-y-2 z-10' style={{ backgroundImage: `url(${home.src})`}}>
       <img  className=' mx-auto px-5 relative flex mt-5 w-auto h-auto' src={Tittle.src}></img>
          <div   className=' relative flex items-center align-auto justify-center'>
            
            <div className=' mt-10 flex relative  w-[1000px] justify-between items-center align-center gap-10 h-1/5 rounded-3xl p-12 mb-24'>
              <div className='rounded-full w-[100px] h-[100px] sm:w-[175px] sm:h-[175px] shadow-lg shadow-gray-400 p-3 cursor-pointer hover:scale-105 ease-in duration-300' >
              
              </div >
              <div className='rounded-full w-[100px] h-[100px] sm:w-[175px] sm:h-[175px] shadow-lg shadow-gray-400 p-3 cursor-pointer hover:scale-105 ease-in duration-300' >
               </div>
                
              <div className='rounded-full w-[100px] h-[100px] sm:w-[175px] sm:h-[175px] shadow-lg shadow-gray-400 p-3 cursor-pointer hover:scale-105 ease-in duration-300' >
                </div>
              </div>
              
            </div>
           
            <div   className=' relative flex items-center align-auto justify-center'>
            
            <div className='   mx-5 relative outline outline-2 bg-[#f5eaab] outline-white/50 md:w-[1000px] w-[500px] justify-between items-center align-center gap-10 h-1/5 rounded-[40px] p-12 mb-24'>
            <img  className=' mx-auto px-5 relative flex mt-5 w-auto h-auto' src={Tittle.src}></img>
            <div className='text-center mt-10 md:grid md:grid-cols-2 '>
                      <div >
                        <h2 > Sponsorship</h2>
                        <h2 className='mt-5 text-white mx-auto outline outline-2 w-4/5 outline-white/50 rounded-3xl bg-[#0e4730]'> 089943568795</h2>
                        <p className='mt-2 text-3xl'>
                        Ines
                      </p>
                      </div>
                      <div>
                      <h2>Media Partnership</h2>
                      <h2 className='mt-5 text-white mx-auto outline outline-2 w-4/5 outline-white/50 rounded-3xl bg-[#0e4730]'> 089943568795</h2>
                      <p className='mt-2 text-3xl'>
                        Ines
                      </p>
                      </div>
                    </div>
             </div>
            </div>
            
          </div>
           {/* Our Past Partner*/}
          <div className=' relative items-center h-full  pt-10 bg-cover translate-y-2 z-0' style={{ backgroundImage: `url(${home.src})`}}>
         
          <img  className=' mt-48 mx-auto px-5 relative flex w-auto h-auto' src={Tittle.src}></img>
          <div   className=' relative flex justify-center'>
          

            <div className=' lg:grid lg:grid-cols-2 gap-10 h-1/5 w-3/4 rounded-3xl justify-center aligncenter p-12 mb-48'>
     
              
            
                <div className=' justify-center align-center items-center p-10 backdrop-blur-3xl rounded-3xl  text-white' >
                  
                    <h2 className='font-bold py-8 text-center w-full'>
                    Sponsor :
                    </h2>
                  
             
                
              </div>
           
                
              <div className=' justify-center align-center items-center p-10 backdrop-blur-3xl rounded-3xl  text-white' >
                  
                  <h2 className='font-bold py-8 text-center w-full'>
                   Media Partner :
                  </h2>
                  </div>
                  </div>
                </div>
            </div>
        
        </div>       
    </>     
  )
}

export default test