import React from "react";
import Head from "next/head";
import Navbar from "../components/Navbar/Navbar";

const contactUs = () => {
  return (
    <>
      <Head>
        <title>GMAD 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../public/favicon.ico" />
      </Head>
      <Navbar />
      <div>contactUs</div>
      <div>contactUs</div>
      <div>contactUs</div>
      <div>contactUs</div>
    </>
  );
};

export default contactUs;
