import React from 'react';
import Head from 'next/head';
import Navbar from '../components/Navbar/Navbar';

function nao() {
	return (
		<>
			<div>
				<Head>
					<title>GMAD 2022</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="../public/favicon.ico" />
				</Head>
				<Navbar />
			</div>
			<div className="h-screen w-full flex items-center justify-center bg-green-dark">
				<div className="text-center w-[40vw]">
					<h1 className="font-chromate text-c-yellow">
						National Accounting Olympiad (NAO)
					</h1>
					<div className="text-white">
						Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent
						consequat vel ligula ac maximus. Aliquam quis erat quam. Mauris vel
						hendrerit elit. Nam sagittis varius ultricies. Nam hendrerit eget
						urna in imperdiet.
					</div>
				</div>
			</div>
			<div className="h-screen w-full p-36 flex items-center justify-center bg-green-light">
				<div className="flex-1 flex flex-col gap-10">
					<h2 className="text-green-dark font-bold">2022</h2>
					<h1 className="font-chromate text-c-yellow">
						Timeline & Information
					</h1>
					<div className="flex gap-10">
						<span className="w-10 h-10 rounded-full bg-c-yellow" />
						<span className="w-10 h-10 rounded-full bg-c-yellow" />
					</div>
				</div>
				<div className="flex-[2]"></div>
			</div>
			<div className="h-[180vh] w-full p-36 flex flex-col gap-60 items-center justify-center bg-green-light">
				<div className="flex flex-col items-center justify-center gap-10 w-[40vw]">
					<h1 className="font-chromate text-c-yellow">Booklet & Guideline</h1>
					<div className="text-white">
						Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent
						consequat vel ligula ac maximus. Aliquam quis erat quam. Mauris vel
						hendrerit elit.
					</div>
					<button className="w-fit px-4 py-2 bg-transparent border-2 border-c-yellow rounded-full text-c-yellow">
						Learn more
					</button>
				</div>

				<div className="flex flex-col items-center justify-center gap-10 w-[40vw]">
					<div className="p-4 h-[20vw] w-[20vw] flex items-center justify-center bg-transparent border-2 border-solid border-c-yellow rounded-full text-c-yellow">
						<h1 className="text-center">Register Now!</h1>
					</div>
				</div>
			</div>
		</>
	);
}

export default nao;
