import React from "react";
import Head from "next/head";
import Navbar from "../components/Navbar/Navbar";
import ProfileCard from "../components/Card/ProfileCard";
import ThemeCard from "../components/Card/ThemeCard"

function Atalks() {
  return (
    <>
      <div>
        <Head>
          <title>GMAD 2022</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="../public/favicon.ico" />
        </Head>
      </div>

      <Navbar />

      {/* section landing page */}
      <section className="  h-screen atalks-bgImg-1">
        <div className="  h-full items-center justify-center mx-auto block md:max-w-screen  atalks-bg-1">
          <div className=" block text-center items-center mx-10 md:mx-80">


            <div className="container relative pt-60 max-w-3xl ">
              <h1 className="text-3xl sm:text-5xl capitalize tracking-widest text-yellow lg:text-7xl font-chromate leading-relaxed outlineText">
                Accounting Talks (A-Talks)
              </h1>
            </div>
            <div className="pt-2 ">
              <p className="text-lg sm:text-2xl text-white font-gogh font-medium">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent consequat vel ligula ac maximus. Aliquam quis erat quam. Mauris vel hendrerit elit. Nam sagittis varius ultricies. Nam hendrerit eget urna in imperdiet.</p>
            </div>
          </div>
        </div>
        </section>
        {/* end section landing page */}

        {/* section subtheme */}
        <section className="h-screen atalks-bgImg-2">
          <div className="atalks-bg-2 h-full">
          <div className="  h-full items-center justify-center mx-auto block md:max-w-screen ">
          <div className=" block text-center items-center mx-10 md:mx-80">


            <div className="container relative pt-28 pb-8 max-w-3xl test-2">
              <h1 className="text-3xl sm:text-5xl capitalize tracking-widest text-yellow lg:text-7xl font-chromate leading-relaxed outlineText">
                Subtheme
              </h1>
            </div>

            <div className="container">
                <ThemeCard />
                <ThemeCard />
            </div>
            
          </div>
        </div>
          </div>
        </section>
        {/* end section subtheme */}

        {/* <div className=" flex justify-center ">
          <ProfileCard />
          <ProfileCard />
          <ProfileCard />
        </div> */}
      
    </>
  );
}

Atalks.getInitialProps = async (ctx) => {
  return {};
};

export default Atalks;
