import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar/Navbar";
import dynamic from "next/dynamic";
import { Suspense } from "react";

const DynamicHeader = dynamic(() =>
  import("../components/Navbar/Navbar").then((mod) => mod.Navbar)
);

export default function Home() {
  return (
    <Suspense fallback={"Loading..."}>
      <DynamicHeader />

      <div>
        <Head>
          <title>GMAD 2022</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="../public/favicon.ico" />
        </Head>
        <Navbar />
      </div>
    </Suspense>
  );
}
